version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_psw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psw_db
    ports:
      - "3302:3306"

    volumes:
      - dbase:/var/lib/mysql
    networks:
      - my-network

  app:
    image: psw_recov_image
    container_name: psw_recov_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/psw_db
    ports:
      - "9090:8080"
    networks:
      - my-network

volumes:
  dbase:

networks:
  my-network:
    driver: bridge

