version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_psw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psw_db
    ports:
      - "3302:3306"

    volumes:
      - dbase:/var/lib/mysql

volumes:
  dbase: